### PR TITLE
Added 'extra_headers' attribute as replacement for session.headers

### PR DESCRIPTION
**Pull request by midnightercz**
Because session was previously shared for whole Downloader and now
it's created for every request, it's not possible to use it as
holder for required http headers. HTTPThreadedDownloader.extra_headers
should be now used as replacement for
HTTPThreadedDownloader.session.headers

### CODE REVIEW

**Comment by midnightercz** [comment]
@ipanova please review. This is prerequisite for next PRs to fix missing Downloader.session.headers

**Comment by ipanova** [comment]
Is is possible to keep session in nectar? I believe it will break some functionality in pulp otherwise.

https://github.com/pulp/pulp/blob/2-master/server/pulp/server/content/sources/model.py#L293
https://github.com/pulp/pulp/blob/2-master/streamer/pulp/streamer/server.py#L256

**Comment by midnightercz** [comment]
I think I can change behaviour to be like:
if Downloader.session object is not None, work with that
otherwise create new session per _fetch called

Does that make sense?

**Comment by midnightercz** [comment]
@ipanova can we merge this?

**Comment by midnightercz** [comment]
This change is only going to fix inconsistency introduces in pulp plugins by previous change

**Pull request merged**
